
import { Box } from '@mui/system'
import Head from 'next/head'
import Image from 'next/image'
import Router, { useRouter } from 'next/router'
import { useState } from 'react'
import Feed from '../components/Feed'
import Navbar from '../components/Navbar'
import fetchFromApi from '../utils/fetchFromApi'

export default function Home(props) {
  console.log(props)
  const router = useRouter()
  function giveMe(name){
    Router.push(`?query=${name}`);
  }
  return (
    <div >
      <Head>
        <title>youtube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{padding:0,overflow:'hidden'}}>
        <Box sx={{background:'#0d0620',height:'100vh', overflowY:'hidden'}}>
          <Navbar />
          <Feed give = {giveMe} initial={router.query.query} data = {props.data} />
        </Box>
      </main>
    </div>
  )
}


export async function getServerSideProps(context) {
    const {query} = context.query 
    const q = query?query:"New"
    const data = await fetchFromApi(`search?part=snippet,id&q=${q}`)
  return {
    props: {data}, // will be passed to the page component as props
  }
}